const mongoose = require('mongoose');

const stockDetailsSchema = new mongoose.Schema(
  {
    watchlist_stock_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Stock',
      required: true,
      index: true,
    },
    symbol: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      uppercase: true,
      index: true,
    },
    company_name: { type: String, default: '' },
    exchange: { type: String, default: '' },
    sector: { type: String, default: '' },
    industry: { type: String, default: '' },
    market_cap: { type: Number, default: 0 },
    enterprise_value: { type: Number, default: 0 },
    current_price: { type: Number, default: 0 },
    previous_close: { type: Number, default: 0 },
    open_price: { type: Number, default: 0 },
    day_high: { type: Number, default: 0 },
    day_low: { type: Number, default: 0 },
    fifty_two_week_high: { type: Number, default: 0 },
    fifty_two_week_low: { type: Number, default: 0 },
    volume: { type: Number, default: 0 },
    average_volume: { type: Number, default: 0 },
    pe_ratio: { type: Number, default: 0 },
    forward_pe: { type: Number, default: 0 },
    peg_ratio: { type: Number, default: 0 },
    price_to_book: { type: Number, default: 0 },
    eps: { type: Number, default: 0 },
    dividend_yield: { type: Number, default: 0 },
    beta: { type: Number, default: 0 },
    shares_outstanding: { type: Number, default: 0 },
    float_shares: { type: Number, default: 0 },
    revenue: { type: Number, default: 0 },
    gross_profit: { type: Number, default: 0 },
    operating_income: { type: Number, default: 0 },
    net_income: { type: Number, default: 0 },
    free_cash_flow: { type: Number, default: 0 },
    total_assets: { type: Number, default: 0 },
    total_liabilities: { type: Number, default: 0 },
    cash: { type: Number, default: 0 },
    debt: { type: Number, default: 0 },
    book_value: { type: Number, default: 0 },
    roe: { type: Number, default: 0 },
    roa: { type: Number, default: 0 },
    profit_margin: { type: Number, default: 0 },
    earnings_date: { type: Date },
    analyst_target_price: { type: Number, default: 0 },
    recommendation: { type: String, default: '' },
    last_synced_at: { type: Date, default: Date.now, index: true },
  },
  {
    timestamps: {
      createdAt: 'created_at',
      updatedAt: 'updated_at',
    },
  }
);

module.exports = mongoose.model('StockDetails', stockDetailsSchema);
